language: python
sudo: required  # need to install dependencies
dist: xenial

python:
  - "3.3"  # try to find lowest supported version
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt59-trusty
  - sudo apt-get update
  - sudo apt-get install -y libnotify-bin qt59base qt59declarative
  - pip install tox-travis

script:
  - tox
