language: python
sudo: required

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis
script: tox

jobs:
  include:
    - stage: package
      install:
      # https://github.com/AppImage/AppImages/issues/187
      - echo "deb http://ppa.launchpad.net/djcj/libcurl-slim/ubuntu xenial main" | sudo tee -a /etc/apt/sources.list
      - echo "deb http://ppa.launchpad.net/djcj/gnutls-patched/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list
      # pin packages to make sure they will be installed whatever version is available from the system
      - cat > /etc/apt/preferences.d/djcj-pin <<EAT
      - Package: *
      - Pin: release o=LP-PPA-djcj-libcurl-slim
      - Pin-Priority: 9999
      -
      - Package: *
      - Pin: release o=LP-PPA-djcj-gnutls-patched
      - Pin-Priority: 9999
      - EAT
      - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4BC359BE72CD1721449C8CC24A5F4FED4B4972B
      - sudo apt-get update
      - sudo apt-get install -y --force-yes  curl
      script:
      - export curdir=$(readlink -f .)
      # install Miniconda, a self contained Python distribution, into AppDir
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - bash Miniconda3-latest-Linux-x86_64.sh -b -p pext.AppDir/usr -f
      # activate Miniconda environment
      - . pext.AppDir/usr/bin/activate
      # install dependencies
      - git clone https://github.com/libgit2/libgit2
      - pushd libgit2; mkdir build/; cd build
      - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
      - make install DESTDIR="${curdir}"/pext.AppDir -j$(nproc)
      - popd
      - pip install PyQt5==5.8 PyOpenGL PyOpenGL_accelerate
      - pip install -U pip
      - pip download pygit2; tar xf pygit2*.tar.gz; pushd pygit2*/
      - python setup.py build_ext --inplace --include-dirs="${curdir}/pext.AppDir/usr/include" --library-dirs="${curdir}/pext.AppDir/usr/lib"
      - python setup.py install
      - popd
      # install Pext
      - python setup.py install
      # set up Desktop file and icon
      - cp pext.desktop pext.AppDir
      - cp pext/images/scalable/pext.svg pext.AppDir
      # patch Desktop file to make sure Pext is executed correctly
      # beware that AppRun chdir()s into usr/ inside the AppImage, that's why one has to remove that from pext's relative path
      - sed -i 's|Exec=.*|Exec=python bin/pext|' pext.AppDir/pext.desktop
      # install AppRun into AppDir
      - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 -O pext.AppDir/AppRun
      - chmod +x pext.AppDir/AppRun
      # clean up unused garbage
      - find pext.AppDir -type f -iname '*.tar.bz2' -delete
      - find pext.AppDir -type f -iname '*.a' -delete
      # fix dependency issues, and remove blacklisted libraries
      - wget https://github.com/AppImage/AppImages/blob/master/functions.sh
      - . functions.sh
      - pushd pext.AppDir
      - copy_deps; copy_deps; copy_deps
      - delete_blacklisted
      - popd
      # build AppImage
      - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
      - chmod +x appimagetool-x86_64.AppImage
      # non-FUSE way of running appimagetool
      - ./appimagetool-x86_64.AppImage --appimage-extract
      - squashfs-root/AppRun pext.AppDir pext-x86_64.AppImage
      # upload AppImage to transfer.sh (temporary, shall be replaced by uploadtool eventually)
      - du -sh -BM pext-x86_64.AppImage
      - curl --upload-file pext-x86_64.AppImage https://transfer.sh/pext-x86_64.AppImage

stages:
  - test
  - package
