language: python
sudo: required  # need to install dependencies

python:
  - "3.3"  # try to find lowest supported version
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update
  - sudo apt-get install -y libnotify-bin qt58base qt58declarative
  - pip install tox-travis

script:
  - /opt/qt*/bin/qt*-env.sh
  #- tox  # disabled to get packaging done
  - mkdir -p pext.AppDir/usr
  - python3 -m venv AppDir/usr
  - . AppDir/usr/bin/activate
  - python3 -m pip install PyQt5==5.8
  - python3 setup.py install
  - cp pext.desktop pext.AppDir
  - cp pext/images/scalable/pext.svg pext.AppDir
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 -O pext.AppDir/AppRun
  - chmod +x pext.AppDir/AppRun
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x appimagetool-x86_64.AppImage
  - ./appimagetool-x86_64.AppImage pext.AppDir pext-x86_64.AppImage
  - curl --upload-file pext-x86_64.AppImage https://transfer.sh/pext-x86_64.AppImage
