language: python
sudo: required  # need to install dependencies

python:
  - "3.3"  # try to find lowest supported version
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

jobs:
  include:
    - stage: test
      install: pip install tox-travis
      script: true  # tox  # disabled to get packaging done
    - stage: package
      script:
      - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - bash Miniconda3-latest-Linux-x86_64.sh -b -p pext.AppDir/usr -f
      - . pext.AppDir/usr/bin/activate
      - conda install -y -c anaconda pyopengl
      - pip install PyQt5==5.8
      - python setup.py install
      - cp pext.desktop pext.AppDir
      - cp pext/images/scalable/pext.svg pext.AppDir
      - sed -i 's|Exec=.*|Exec=python bin/pext|' pext.AppDir/pext.desktop
      - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64 -O pext.AppDir/AppRun
      - chmod +x pext.AppDir/AppRun
      - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
      - chmod +x appimagetool-x86_64.AppImage
      - ./appimagetool-x86_64.AppImage pext.AppDir pext-x86_64.AppImage
      - curl --upload-file pext-x86_64.AppImage https://transfer.sh/pext-x86_64.AppImage
