language: python
sudo: required  # need to install dependencies
dist: xenial

python:
  - "3.3"  # try to find lowest supported version
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - sudo apt-get update
  - sudo apt-get install -y libnotify-bin python3-pyqt5.qtquick qml-module-qtquick-controls
  - pip install tox-travis

script:
  - tox
