language: python
sudo: required  # need to install dependencies

python:
  - "3.3"  # try to find lowest supported version
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update
  - sudo apt-get install -y libnotify-bin qt58base qt58declarative
  - pip install tox-travis

script:
  - /opt/qt*/bin/qt*-env.sh
  #- tox  # disabled to get packaging done
  - mkdir -p pext.AppDir/usr
  - python3 -m venv AppDir/usr
  - . AppDir/usr/bin/activate
  - pip3 install PyQt5==5.8
  - python3 setup.py install

